<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>版权说明</title>
</head>
<body>
<h2>Yummy!用户协议</h2>
<h4>一、条款</h4>
<h4>二、用户服务</h4>
<h4>三、商家管理</h4>
<h4>四、交易规则</h4>
<h4>五、用户的权利和义务</h4>
<h4>六、Yummy!的权利和义务</h4>
<h4>七、用户信息</h4>
<h4>八、特别声明</h4>
<h4>九、知识产权</h4>
<h4>十、客户服务</h4>
<h4>十一、协议的变更和终止</h4>
<h4>十二、违约责任</h4>
<h4>十三、争议解决</h4>
</body>
</html>
